FROM  ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

MAINTAINER sky

# Update sources
RUN apt-get update -y

## install httpd
RUN apt-get -y install apache2 icu-devtools openssh-server supervisor software-properties-common 

## install php 5.6
RUN export LANG=C.UTF-8 && add-apt-repository ppa:ondrej/php5-5.6

RUN apt-get -y install php5

# config httpd.conf
RUN sed -i \
        -e "151s/AllowOverride None/AllowOverride All/" \
        /etc/apache2/apache2.conf

RUN sed -i \
        -e "s~Listen 80~Listen 80\nListen 8080~" \
        /etc/apache2/ports.conf

RUN sed -i \
        -e "s/DirectoryIndex index.html/DirectoryIndex index.html Default.html Default.htm/" \
        /etc/apache2/mods-available/dir.conf

# Reconfigure PHP
RUN sed -i \
        -e 's/max_input_time = 60/max_input_time = 180/g' \
        -e 's/memory_limit = 128M/memory_limit = 1024M/g' \
        -e 's/post_max_size = 8M/post_max_size = 2100M/g' \
        -e 's/upload_max_filesize = 2M/upload_max_filesize = 2048M/g' \
        -e 's#;curl.cainfo=#curl.cainfo = /etc/.cacert/cacert.pem#g' \
        -e 's#;openssl.cafile=#openssl.cafile = /etc/.cacert/cacert.pem#g' \
        /etc/php5/apache2/php.ini


# doload cacert.pem to /etc/.cacert
RUN apt-get -y install wget
RUN wget -P /etc/.cacert https://curl.haxx.se/ca/cacert.pem

RUN apt-get -y install curl 
# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

EXPOSE 80 443 22

ADD run /var/www/html/website-website

RUN cd /usr/share/nginx/html/website_com && ./init && 1 && y

COPY website_com.conf /etc/httpd/conf.d/website_com.conf

COPY supervisord.conf /etc/supervisord.conf


# 容器启动命令
CMD ["/usr/bin/supervisord"]








